services:
  - type: web
    name: nutriconecta
    runtime: docker
    region: oregon
    plan: free
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: nutriconecta-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: nutriconecta-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: nutriconecta-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: nutriconecta-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: nutriconecta-db
          property: password

databases:
  - name: nutriconecta-db
    databaseName: nutriconecta
    user: nutriconecta
    plan: free
