spring.application.name=nutriconecta

# Perfil padrão: roda localmente com H2 sem precisar instalar banco.
spring.datasource.url=jdbc:h2:file:./data/nutriconecta;AUTO_SERVER=TRUE;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.thymeleaf.cache=false
server.port=${PORT:8080}
